langaugeBar.add_command(label="English"   ,command=getLang("en")),
languageBar.add_command(label="Polish"    ,command=getLang("pl")),
languageBar.add_command(label="Turkish"   ,command=getLang("tr")),
languageBar.add_command(label="Russian"   ,command=getLang("ru")),
languageBar.add_command(label="Ukranian"  ,command=getLang("uk")),
languageBar.add_command(label="Czech"     ,command=getLang("cs")),
languageBar.add_command(label="Portuguese",command=getLang("pt")),
languageBar.add_command(label="Greek"     ,command=getLang("el")),
languageBar.add_command(label="Italian"   ,command=getLang("it")),
languageBar.add_command(label="Vietnamese",command=getLang("vi")),
languageBar.add_command(label="French"    ,command=getLang("fr")),
languageBar.add_command(label="Spanish"   ,command=getLang("es")),